apiVersion: apps/v1
kind: Deployment
metadata:
  name: i360-proto
  labels:
    app: i360
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i360
  template:
    metadata:
      labels:
        app: i360
    spec:
      containers:
      - name: tools
        image: nginx:1.14.2
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /index.html
            port: 81
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 81
        resources:
          requests:
            memory: 10Mi
          limits:
            memory: 64Mi
            cpu: 10m
        volumeMounts:
            - name: tools-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: tools-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
              readOnly: true
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 10Mi
          limits:
            memory: 64Mi
            cpu: 10m
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: tools-conf
          configMap:
            name: tools-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: tools-html
          configMap:
            name: tools-conf
            items:
              - key: index.html
                path: index.html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            proxy_pass   http://127.0.0.1:81;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tools-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       81;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html; #Change this line
            index  index.html index.htm;
        }
      }
    }
  index.html: |
    <html><h1>This is the sidecar poc</h1></html>
---
apiVersion: v1
kind: Service
metadata:
  name: i360-service
spec:
  selector:
    app: i360
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80